//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace au.util.comctl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("au.util.comctl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap browseFile {
            get {
                object obj = ResourceManager.GetObject("browseFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browseFolder {
            get {
                object obj = ResourceManager.GetObject("browseFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calc {
            get {
                object obj = ResourceManager.GetObject("calc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calcLarge {
            get {
                object obj = ResourceManager.GetObject("calcLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only ListView controls in details view can be sorted using this method..
        /// </summary>
        internal static string DetailsViewRequiredMessage {
            get {
                return ResourceManager.GetString("DetailsViewRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Selection.
        /// </summary>
        internal static string FilenameBoxMessageBoxCaption {
            get {
                return ResourceManager.GetString("FilenameBoxMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} does not exist..
        /// </summary>
        internal static string FileNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("FileNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File specified does not exist:
        ///{0}.
        /// </summary>
        internal static string FileNotFoundMessageBoxMessage {
            get {
                return ResourceManager.GetString("FileNotFoundMessageBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Selection.
        /// </summary>
        internal static string FoldernameBoxMessageBoxCaption {
            get {
                return ResourceManager.GetString("FoldernameBoxMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder {0} does not exist..
        /// </summary>
        internal static string FolderNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("FolderNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder specified does not exist:
        ///{0}.
        /// </summary>
        internal static string FolderNotFoundMessageBoxMessage {
            get {
                return ResourceManager.GetString("FolderNotFoundMessageBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} is not contained within {0}..
        /// </summary>
        internal static string PathMismatchExceptionMessage {
            get {
                return ResourceManager.GetString("PathMismatchExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File must be contained in base path:
        ///{0}.
        /// </summary>
        internal static string PathMismatchMessageBoxMessage {
            get {
                return ResourceManager.GetString("PathMismatchMessageBoxMessage", resourceCulture);
            }
        }
    }
}
